name: CI/CD Infrasctrucure Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  

    env:
      LOCATION: ${{ vars.LOCATION }}
      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      VNET_NAME: ${{ vars.VNET_NAME }}
      SUBNET_FUNCTIONS: ${{ vars.SUBNET_FUNCTIONS }}
      SUBNET_PRIVATE_ENDPOINT: ${{ vars.SUBNET_PRIVATE_ENDPOINT }}
      SERVICEBUS_NAMESPACE: ${{ vars.SERVICEBUS_NAMESPACE }}

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Login no Azure (OIDC)
        uses: azure/login@v2
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Criar Infraestrutura
        run: |
          chmod +x infra.sh
          ./infra.sh

      - name: Configurar Rede
        run: |
          chmod +x rede.sh
          ./rede.sh
